/**
 * 标签系统相关类型定义
 * Requirements: 7.1, 7.2, 7.3, 7.4
 */

/** 标签类别 */
export enum TagCategory {
  GAME_TYPE = 'game_type',
  AGE_GROUP = 'age_group',
  PLAYER_COUNT = 'player_count',
  ERA = 'era',
  THEME = 'theme',
  CUSTOM = 'custom',
}

/** 标签 */
export interface Tag {
  id: string;
  name: string;
  category: TagCategory;
}

/** 剧本-标签关联 */
export interface ScriptTag {
  scriptId: string;
  tagId: string;
  isAutoGenerated: boolean;
}
